spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/